name: ðŸš€ Deploy website on push
on:
  push:
    branches: [main,master]
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
    - uses: actions/checkout@v2
      with:
        repository: 'portfolio'
        ref: 'main'
    
    - name: ðŸ“‚ Sync files
      uses: /home/runner/work/_action/kuntal811/portfolio@main
      with:
        branch: main
        server: ${{secrets.ftp_host}}
        username: ${{secrets.ftp_username}}
        password: ${{ secrets.ftp_password }}
        port: ${{secrets.ftp_port}}
        target: "/public_html/"
